name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bug'
  default: patch

autolabeler:
  - label: 'feature'
    branch:
      - '/feature/.+/'
    title:
      - '/feature:.+/'
      - '/feat:.+/'
  - label: 'fix'
    branch:
      - '/fix/.+/'
    title:
      - '/fix:.+/'
  - label: 'chore'
    branch:
      - '/chore/.+/'
    title:
      - '/chore:.+/'
  - label: 'refactor'
    title:
      - '/refactor:.+/'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance & Internal'
    labels:
      - 'chore'
      - 'refactor'
      - 'documentation'
      - 'style'
      - 'test'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/MauAlvarado43/open-valobook/compare/$PREVIOUS_TAG...$NEXT_TAG
